language: c
compiler: gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y check
  - sudo pip install --user cpp-coveralls
script:
  - ./autogen.sh && ./configure --enable-gcov && make check
after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
