language: c
compiler: gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y check
  - sudo pip install cpp-coveralls
script:
  - ./autogen.sh && ./configure && make check
after_success:
- coveralls --gcov-options '\-lp' -r src -b .
